id: IA4454FBC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:34:06+00:00'
last_modified: '2022-06-10T11:34:04.965394+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28780
  title: ལམ་འབྲས་ལམ་རིམ་སྨོན་ལམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7F88:
      image_group_id: I1CZ1036
      title: ''
      total_pages: 36
      order: 1
      base_file: 7F88.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
